[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"

[dependencies]
actix-web = "4.10.2"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }


[dev-dependencies]
reqwest = "0.12.15"
